all: true
dir: 'mocks'
filename: 'mock_{{.InterfaceName}}.go'
outpkg: 'mocks'
packages:
  github.com/mamochiro/go-microservice-template/internal/domain/repository:
  github.com/mamochiro/go-microservice-template/internal/domain/service:
