@baseUrl = http://localhost:3003/api/v1

### Health Check
GET http://localhost:3003/health

### Metrics
GET http://localhost:3003/metrics

### User Login
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "securepassword123"
}

### Access Token from Login
@authToken = {{login.response.body.access_token}}

### Create User (Needs Auth)
# @name createUser
POST {{baseUrl}}/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "username": "johndoe",
    "email": "john@example.com",
    "password": "securepassword123"
}

### List Users (Needs Auth)
GET {{baseUrl}}/users?page=1&limit=10
Authorization: Bearer {{authToken}}

### Get User by ID (Needs Auth)
@userId = {{createUser.response.body.id}}
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}

### Update User (Needs Auth)
PUT {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "username": "john_updated",
    "email": "john_updated@example.com"
}

### Delete User (Needs Auth)
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
