app:
  name: "go-microservice-template"
  port: "3003"
  env: "development"

postgres:
  host: "localhost"
  port: "5434"
  user: "user"
  password: "password"
  dbname: "microservice"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

email:
  from: "onboarding@resend.dev"

