version: '3'

vars:
  APP_NAME: go-microservice-template
  MAIN_PATH: cmd/api/main.go
  BIN_PATH: bin/{{.APP_NAME}}

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o {{.BIN_PATH}} {{.MAIN_PATH}}

  run:
    desc: Run the application
    cmds:
      - go run {{.MAIN_PATH}}

  wire:
    desc: Generate dependency injection code
    cmds:
      - cd internal/app && wire

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  integration-test:
    desc: Run integration tests
    cmds:
      - POSTGRES_DBNAME=microservice_test go test -v -tags=integration ./tests/integration/...

  docker-up:
    desc: Start docker-compose
    cmds:
      - docker-compose up -d

  docker-down:
    desc: Stop docker-compose
    cmds:
      - docker-compose down

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  mock:
    desc: Generate mocks
    cmds:
      - mockery
