// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/mamochiro/go-microservice-template/internal/config"
	"github.com/mamochiro/go-microservice-template/internal/domain/service"
	"github.com/mamochiro/go-microservice-template/internal/infrastructure/cache"
	"github.com/mamochiro/go-microservice-template/internal/infrastructure/database"
	"github.com/mamochiro/go-microservice-template/internal/infrastructure/repository"
	"github.com/mamochiro/go-microservice-template/internal/transport/http/handler"
	"github.com/mamochiro/go-microservice-template/internal/transport/http/router"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (http.Handler, func(), error) {
	db, cleanup, err := database.NewPostgresDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := cache.NewRedisClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	healthHandler := handler.NewHealthHandler(db, client)
	userRepo := repository.NewUserRepository(db)
	cacheRepository := cache.NewCacheRepository(client)
	userRepository := repository.NewCachedUserRepository(userRepo, cacheRepository)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	authService := service.NewAuthService(userRepository, cfg)
	authHandler := handler.NewAuthHandler(authService)
	httpHandler := router.NewRouter(cfg, healthHandler, userHandler, authHandler)
	return httpHandler, func() {
		cleanup2()
		cleanup()
	}, nil
}
